name = "lettuce-pokedex"

main = "./.svelte-kit/.cloudflare/worker.js"
site.bucket = "./.svelte-kit/.cloudflare/public"

build.command = "pnpm build"

compatibility_date = "2021-11-12"
workers_dev = true